#!/usr/bin/env python
"""Generate the compact The Plant Phenome Journal manuscript number file.

Only canonical, repaired outputs are read.  The script intentionally avoids the
legacy manuscript generator, whose optional-result dependencies are incomplete
in the review archive.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "manuscript/numbers.tex"
PER_PLANT = ROOT / "manuscript/per_plant_table.tex"


def read_json(path: str) -> dict:
    return json.loads((ROOT / path).read_text(encoding="utf-8"))


def fmt(value: float | int, digits: int = 2) -> str:
    if isinstance(value, (int, np.integer)):
        return str(int(value))
    return f"{float(value):.{digits}f}"


def main() -> None:
    lines: list[str] = [
        "% Generated by manuscript/generate_numbers.py; do not edit.",
    ]

    def put(name: str, value: object) -> None:
        lines.append(rf"\newcommand{{\{name}}}{{{value}}}")

    manual = read_json("data/processed/manual_poles_2021/summary.json")
    put("ManualPoleXMLFiles", manual["xml_files"])
    put("ManualPoleImages", manual["retained_unique_images"])
    put("ManualPoleAnnotations", manual["annotations"])
    put("ManualPoleUsable", manual["usable_annotations"])
    put("ManualPoleUnusable", manual["unusable_annotations"])
    put("SupportPoleLengthFt", fmt(manual["physical_length_ft"], 0))
    put("SupportPoleLengthCm", fmt(manual["physical_length_cm"], 1))
    put("FieldMarkIntervalIn", fmt(manual["field_mark_interval_in"], 0))
    put("FieldMarkIntervalsPerRow", manual["field_mark_intervals_per_row"])
    put("AdjacentRowSpacingIn", fmt(manual["adjacent_row_spacing_in"], 0))

    pole_repeatability = read_json("outputs/pole_repeatability_2021/summary.json")
    pole_repeatability_design = pole_repeatability["design"]
    put("PoleRepeatabilitySeries", pole_repeatability_design["repeated_row_pole_series"])
    put("PoleRepeatabilityRows", pole_repeatability_design["stationary_camera_rows"])
    put("PoleRepeatabilityAnnotations", pole_repeatability_design["usable_annotations"])
    put("PoleRepeatabilityMedianCV", fmt(pole_repeatability["median_cv_percent"]))
    put("PoleRepeatabilityMedianCVLo", fmt(pole_repeatability["median_cv_row_cluster_ci95_percent"][0]))
    put("PoleRepeatabilityMedianCVHi", fmt(pole_repeatability["median_cv_row_cluster_ci95_percent"][1]))
    put("PoleRepeatabilityNinetiethCV", fmt(pole_repeatability["p90_cv_percent"]))
    put("PoleRepeatabilityBelowFive", pole_repeatability["series_below_5_percent_cv"])
    put("PoleRepeatabilityMaximumCV", fmt(pole_repeatability["maximum_cv_percent"]))

    all_plants = read_json("outputs/filter_height_sam_2021/all_plants_primary.json")
    whole = all_plants["whole_season_all_plants"]
    after_first = all_plants["after_first_image_all_plants"]
    endpoint = all_plants["endpoint_all_plants"]
    sf, bf = whole["single_frame"], whole["online_filter"]
    boot = whole["paired_row_cluster_bootstrap"]
    put("FieldN", sf["n"])
    put("FieldPlants", sf["plants"])
    put("FieldRows", sf["rows"])
    put("FieldSingleBias", fmt(sf["bias_cm"]))
    put("FieldSingleMAE", fmt(sf["mae_cm"]))
    put("FieldSingleRMSE", fmt(sf["rmse_cm"]))
    put("FieldBayesBias", fmt(bf["bias_cm"]))
    put("FieldBayesMAE", fmt(bf["mae_cm"]))
    put("FieldBayesRMSE", fmt(bf["rmse_cm"]))
    put("FieldMAEGain", fmt(boot["mae_improvement_cm"]))
    put("FieldMAEGainLo", fmt(boot["ci95_cm"][0]))
    put("FieldMAEGainHi", fmt(boot["ci95_cm"][1]))
    put("FieldBootstrapReplicates", f"{boot['replicates']:,}")
    put("FieldEndpointN", endpoint["single_frame"]["n"])
    put("FieldEndpointSingleBias", fmt(endpoint["single_frame"]["bias_cm"]))
    put("FieldEndpointSingleMAE", fmt(endpoint["single_frame"]["mae_cm"]))
    put("FieldEndpointSingleRMSE", fmt(endpoint["single_frame"]["rmse_cm"]))
    put("FieldEndpointBayesBias", fmt(endpoint["online_filter"]["bias_cm"]))
    put("FieldEndpointBayesMAE", fmt(endpoint["online_filter"]["mae_cm"]))
    put("FieldEndpointBayesRMSE", fmt(endpoint["online_filter"]["rmse_cm"]))
    put("FieldEndpointGain", fmt(endpoint["paired_row_cluster_bootstrap"]["mae_improvement_cm"]))
    put("FieldEndpointGainLo", fmt(endpoint["paired_row_cluster_bootstrap"]["ci95_cm"][0]))
    put("FieldEndpointGainHi", fmt(endpoint["paired_row_cluster_bootstrap"]["ci95_cm"][1]))

    put("FieldAfterFirstN", after_first["single_frame"]["n"])
    put("FieldAfterFirstPlants", after_first["single_frame"]["plants"])
    put("FieldAfterFirstRows", after_first["single_frame"]["rows"])
    put("FieldAfterFirstSingleMAE", fmt(after_first["single_frame"]["mae_cm"]))
    put("FieldAfterFirstBayesMAE", fmt(after_first["online_filter"]["mae_cm"]))
    put("FieldAfterFirstGain", fmt(after_first["paired_row_cluster_bootstrap"]["mae_improvement_cm"]))
    put("FieldAfterFirstGainLo", fmt(after_first["paired_row_cluster_bootstrap"]["ci95_cm"][0]))
    put("FieldAfterFirstGainHi", fmt(after_first["paired_row_cluster_bootstrap"]["ci95_cm"][1]))

    field = pd.read_csv(
        ROOT / "outputs/filter_height_sam_2021/filtered_height_sam__phi1.0_plus_pole_growth_field.csv"
    )
    field_uncertainty = read_json("outputs/manual_height_uncertainty_2021/summary.json")
    field_intervals = {
        int(round(100 * row["nominal_coverage"])): row
        for row in field_uncertainty["intervals"]
    }
    field_80 = field_intervals[80]
    field_95 = field_intervals[95]
    put("FieldDates", field["date"].nunique())
    put("FieldCovered", field_95["covered"])
    put("FieldCoverage", fmt(100 * field_95["empirical_coverage"], 1))
    put("FieldIntervalWidth", fmt(field_95["mean_width_cm"], 1))
    put("FieldIntervalMedianWidth", fmt(field_95["median_width_cm"], 1))
    for level, row in ((80, field_80), (95, field_95)):
        suffix = "Eighty" if level == 80 else "NinetyFive"
        put(f"FieldCovered{suffix}", row["covered"])
        put(f"FieldCoverage{suffix}", fmt(100 * row["empirical_coverage"], 1))
        put(f"FieldCoverage{suffix}Lo", fmt(100 * row["coverage_row_cluster_ci95"][0], 1))
        put(f"FieldCoverage{suffix}Hi", fmt(100 * row["coverage_row_cluster_ci95"][1], 1))
        put(f"FieldIntervalWidth{suffix}", fmt(row["mean_width_cm"], 1))
        put(f"FieldIntervalWidth{suffix}Lo", fmt(row["mean_width_row_cluster_ci95_cm"][0], 1))
        put(f"FieldIntervalWidth{suffix}Hi", fmt(row["mean_width_row_cluster_ci95_cm"][1], 1))
    end = field[field["is_endpoint"].astype(bool)].copy()
    end_covered = end["height_true"].between(end["posterior_q025_cm"], end["posterior_q975_cm"])
    end_width = end["posterior_q975_cm"] - end["posterior_q025_cm"]
    put("FieldEndpointCovered", int(end_covered.sum()))
    put("FieldEndpointCoverage", fmt(100 * end_covered.mean(), 1))
    put("FieldEndpointIntervalWidth", fmt(end_width.mean(), 1))

    pix = read_json("outputs/pixel_validation_2021/summary.json")
    put("PixelImages", pix["n_images"])
    put("PixelInstances", pix["n_gt_instances"])
    put("PixelMatched", pix["n_matched"])
    put("PixelDetectionRate", fmt(100 * pix["detection_rate"], 1))
    put("PixelHeightMAEPx", fmt(pix["height_mae_px"], 1))
    put("PixelHeightBiasPx", fmt(pix["height_bias_px"], 1))
    put("PixelHeightRMSECm", fmt(pix["height_rmse_cm"]))
    put("PixelHeightMAECm", fmt(pix["height_mae_cm"]))
    put("PixelHeightBiasCm", fmt(pix["height_bias_cm"]))
    put("PixelHeightCorr", fmt(pix["height_corr"], 3))
    put("PixelCmPerPx", fmt(pix["cm_per_px"], 6))
    put("PixelTopMAEPx", fmt(pix["top_kpt_mae_px"], 1))
    put("PixelRootMAEPx", fmt(pix["root_kpt_mae_px"], 1))

    hold = read_json("outputs/pole_holdout_validation_daily/bootstrap_ci.json")
    dev = hold["development_interpolation_alternating"]
    test = hold["locked_test_interpolation_alternating"]
    put("PoleDevCameras", dev["n_cameras"])
    put("PoleDevN", dev["n_obs"])
    put("PoleDevMAEIn", fmt(dev["mae_in"], 3))
    put("PoleDevMAELoIn", fmt(dev["ci95_lo_in"], 3))
    put("PoleDevMAEHiIn", fmt(dev["ci95_hi_in"], 3))
    put("PoleTestCameras", test["n_cameras"])
    put("PoleTestN", test["n_obs"])
    put("PoleTestMAEIn", fmt(test["mae_in"], 3))
    put("PoleTestMAELoIn", fmt(test["ci95_lo_in"], 3))
    put("PoleTestMAEHiIn", fmt(test["ci95_hi_in"], 3))

    down = pd.read_csv(ROOT / "outputs/pole_downward_bias/downward_extrapolation_errors.csv")
    one_band = down[np.isclose(down["below_ft"], 1.0)]
    for offset, (prefix, data) in enumerate(
        [("DownAll", down), ("DownOneBand", one_band)]
    ):
        put(prefix + "N", len(data))
        put(prefix + "Images", data["image_id"].nunique())
        put(prefix + "Cameras", data["camera"].nunique())
        put(prefix + "BiasCm", fmt(data["error_cm"].mean()))
        put(prefix + "MAECm", fmt(data["error_cm"].abs().mean()))
        put(prefix + "RMSECm", fmt(np.sqrt(np.mean(data["error_cm"] ** 2))))
        by_camera = (
            data.groupby("camera")["error_cm"]
            .agg(
                bias="mean",
                mae=lambda values: values.abs().mean(),
                mse=lambda values: np.mean(values**2),
            )
            .reset_index()
        )
        put(prefix + "CameraBiasCm", fmt(by_camera["bias"].mean()))
        put(prefix + "CameraMAECm", fmt(by_camera["mae"].mean()))
        put(prefix + "CameraRMSECm", fmt(np.sqrt(by_camera["mse"].mean())))
        rng = np.random.default_rng(20260910 + offset)
        draw = rng.integers(0, len(by_camera), size=(20_000, len(by_camera)))
        boot_mae = by_camera["mae"].to_numpy()[draw].mean(axis=1)
        put(prefix + "CameraMAELoCm", fmt(np.quantile(boot_mae, 0.025)))
        put(prefix + "CameraMAEHiCm", fmt(np.quantile(boot_mae, 0.975)))

    guessed_summary = read_json(
        "outputs/online_study/pole_camera_bayesian_daily_guessed_revised/evaluation_summary.json"
    )
    calibrated_summary = read_json(
        "outputs/online_study/pole_camera_bayesian_daily_revised/evaluation_summary.json"
    )
    hyper = read_json("outputs/online_study/calibrated_growth_hyperparameters_daily.json")
    guessed_post = pd.read_csv(
        ROOT / "outputs/online_study/pole_camera_bayesian_daily_guessed_revised/online_bayesian_height_posteriors.csv",
        low_memory=False,
    )
    calibrated_post = pd.read_csv(
        ROOT / "outputs/online_study/pole_camera_bayesian_daily_revised/online_bayesian_height_posteriors.csv",
        low_memory=False,
    )
    guessed_later = guessed_post[guessed_post["online_sequence_number"] > 1]
    calibrated_later = calibrated_post[calibrated_post["online_sequence_number"] > 1]
    assembled = pd.read_csv(
        ROOT / "data/processed/online_longitudinal_pole_heights_daily.csv",
        low_memory=False,
    )
    calibrations = pd.read_csv(
        ROOT / "data/processed/automatic_pole_calibrations_daily.csv",
        low_memory=False,
    )
    put("PoleDailyImages", calibrations["image_id"].nunique())
    put("PoleDailyPassing", int(calibrations["pole_fit_pass"].astype(bool).sum()))
    put("AssembledImages", assembled["image_id"].nunique())
    put("AssembledRows", len(assembled))
    put("AssembledCameras", assembled["camera_genotype"].nunique())
    put("AssembledPlants", assembled["plant_uid"].nunique())
    guessed_width = guessed_later["predictive_q975_cm"] - guessed_later["predictive_q025_cm"]
    calibrated_width = calibrated_later["predictive_q975_cm"] - calibrated_later["predictive_q025_cm"]
    put("PoleStreamRows", len(calibrated_post))
    put("PoleStreamForecasts", len(calibrated_later))
    put("PoleStreamPlants", calibrated_post["plant_uid"].nunique())
    put("PoleStreamCameras", calibrated_post["camera_genotype"].nunique())
    put("PoleStreamImages", calibrated_post["image_id"].nunique())
    put("GuessedCoverage", fmt(100 * guessed_summary["predictive_95_interval_coverage_of_image_measurement"], 1))
    put("CalibratedCoverage", fmt(100 * calibrated_summary["predictive_95_interval_coverage_of_image_measurement"], 1))
    put("GuessedWidth", fmt(guessed_width.mean(), 1))
    put("GuessedMedianWidth", fmt(guessed_width.median(), 1))
    put("CalibratedWidth", fmt(calibrated_width.mean(), 1))
    put("CalibratedMedianWidth", fmt(calibrated_width.median(), 1))
    put("ProcessHeightSD", fmt(hyper["process_height_sd_cm_sqrt_day"], 3))
    put("OutlierProbability", fmt(hyper["outlier_probability"], 4))
    put("OutlierSD", fmt(hyper["outlier_sd_cm"], 2))
    put("CalibrationIntervals", hyper["n_weekly_intervals"])

    uncertainty = read_json("outputs/uncertainty_revision/summary.json")
    uncertainty_rows = {
        (row["model"], row["split"]): row for row in uncertainty["summary"]
    }
    interval_rows = {
        (row["model"], row["split"], int(round(100 * row["nominal_coverage"]))): row
        for row in uncertainty["intervals"]
    }
    calibrated_all = uncertainty_rows[("unit_consistent", "all")]
    calibrated_dev = uncertainty_rows[("unit_consistent", "2024_development")]
    calibrated_test = uncertainty_rows[("unit_consistent", "2025_locked_test")]
    put("CalibratedWIS", fmt(calibrated_all["mean_wis_cm"]))
    put("CalibratedLogScore", fmt(calibrated_all["mean_log_score"], 3))
    put("UncertaintyDevN", calibrated_dev["n"])
    put("UncertaintyDevCameras", calibrated_dev["cameras"])
    put("UncertaintyDevPlants", calibrated_dev["plants"])
    put("UncertaintyDevWIS", fmt(calibrated_dev["mean_wis_cm"]))
    put("UncertaintyTestN", calibrated_test["n"])
    put("UncertaintyTestCameras", calibrated_test["cameras"])
    put("UncertaintyTestPlants", calibrated_test["plants"])
    put("UncertaintyTestBias", fmt(calibrated_test["bias_cm"]))
    put("UncertaintyTestMAE", fmt(calibrated_test["mae_cm"]))
    put("UncertaintyTestRMSE", fmt(calibrated_test["rmse_cm"]))
    put("UncertaintyTestWIS", fmt(calibrated_test["mean_wis_cm"]))
    put("UncertaintyTestLogScore", fmt(calibrated_test["mean_log_score"], 3))
    level_words = {50: "Fifty", 80: "Eighty", 90: "Ninety", 95: "NinetyFive"}
    for level in (50, 80, 90, 95):
        dev_interval = interval_rows[("unit_consistent", "2024_development", level)]
        test_interval = interval_rows[("unit_consistent", "2025_locked_test", level)]
        suffix = level_words[level]
        put(f"UncertaintyDevCoverage{suffix}", fmt(100 * dev_interval["empirical_coverage"], 1))
        put(f"UncertaintyDevWidth{suffix}", fmt(dev_interval["mean_width_cm"], 1))
        put(f"UncertaintyTestCoverage{suffix}", fmt(100 * test_interval["empirical_coverage"], 1))
        put(f"UncertaintyTestWidth{suffix}", fmt(test_interval["mean_width_cm"], 1))
    put("UncertaintyTestMedianWidthNinetyFive", fmt(interval_rows[("unit_consistent", "2025_locked_test", 95)]["median_width_cm"], 1))

    def forecast(summary: dict, estimator: str) -> dict:
        return next(x for x in summary["forecast_metrics"] if x["estimator"] == estimator)

    bayes_forecast = forecast(calibrated_summary, "bayesian_one_step_predictive_mean")
    last_forecast = forecast(calibrated_summary, "last_observation_carried_forward")
    linear_forecast = forecast(calibrated_summary, "two_point_linear_extrapolation")
    put("ForecastBayesMAE", fmt(bayes_forecast["mae_cm"]))
    put("ForecastBayesRMSE", fmt(bayes_forecast["rmse_cm"]))
    put("ForecastLastMAE", fmt(last_forecast["mae_cm"]))
    put("ForecastLastRMSE", fmt(last_forecast["rmse_cm"]))
    put("ForecastLinearMAE", fmt(linear_forecast["mae_cm"]))
    put("ForecastLinearRMSE", fmt(linear_forecast["rmse_cm"]))

    audit = read_json("outputs/online_study/causality_audit_daily.json")
    put("CausalPrefixes", audit["checked_prefixes"])
    put("CausalRows", f"{audit['checked_rows_cumulative']:,}")
    put("CausalMismatches", audit["mismatch_count"])

    prior = pd.read_csv(ROOT / "outputs/candidate_ambiguity_simulation/prior_in_detection_sim.csv")
    prior_summary = read_json(
        "outputs/candidate_ambiguity_simulation/prior_in_detection_sim_summary.json"
    )
    values = dict(zip(prior["prior"], prior["height_rmse_cm"]))
    put("PriorNoneRMSE", fmt(values["none"]))
    put("PriorPostRMSE", fmt(values["on output"]))
    put("PriorInsideRMSE", fmt(values["in detection"]))
    put("PriorInsideReduction", fmt(100 * (values["none"] - values["in detection"]) / values["none"], 1))
    put("PriorSimulationPlants", prior_summary["plants"])
    put("PriorSimulationScenarios", prior_summary["scenarios"])
    put("PriorSpuriousProbability", fmt(prior_summary["spurious_candidate_probability"], 2))
    put("PriorTruthSelectionRate", fmt(100 * prior_summary["truth_closest_selection_rate"], 1))
    prior_boot = prior_summary["plant_cluster_bootstrap"]
    put("PriorNoneRMSELo", fmt(prior_boot["single_frame_rmse_cm"]["ci95"][0]))
    put("PriorNoneRMSEHi", fmt(prior_boot["single_frame_rmse_cm"]["ci95"][1]))
    put("PriorPostRMSELo", fmt(prior_boot["post_hoc_rmse_cm"]["ci95"][0]))
    put("PriorPostRMSEHi", fmt(prior_boot["post_hoc_rmse_cm"]["ci95"][1]))
    put("PriorInsideRMSELo", fmt(prior_boot["prior_in_detection_rmse_cm"]["ci95"][0]))
    put("PriorInsideRMSEHi", fmt(prior_boot["prior_in_detection_rmse_cm"]["ci95"][1]))
    put("PriorVsPostGain", fmt(prior_boot["post_hoc_minus_prior_in_detection_rmse_cm"]["mean"]))
    put("PriorVsPostGainLo", fmt(prior_boot["post_hoc_minus_prior_in_detection_rmse_cm"]["ci95"][0]))
    put("PriorVsPostGainHi", fmt(prior_boot["post_hoc_minus_prior_in_detection_rmse_cm"]["ci95"][1]))

    real_audit = read_json("outputs/real_image_candidate_ablation_2021/summary.json")
    real_metrics = {row["method"]: row for row in real_audit["metrics"]}
    real_single = real_metrics["Single frame"]
    real_post = real_metrics["Identical candidates plus post-detection filter"]
    real_prior = real_metrics["Height prior in candidate scoring plus identical filter"]
    put("RealAuditN", real_audit["design"]["plant_dates"])
    put("RealAuditCameras", real_audit["design"]["cameras"])
    put("RealAuditTracks", real_audit["design"]["plant_tracks"])
    put("RealAuditAgreement", fmt(100 * real_audit["selection_agreement"], 1))
    put("RealAuditSingleMAE", fmt(real_single["mae_cm"]))
    put("RealAuditPostMAE", fmt(real_post["mae_cm"]))
    put("RealAuditPriorMAE", fmt(real_prior["mae_cm"]))
    put("RealAuditSingleRMSE", fmt(real_single["rmse_cm"]))
    put("RealAuditPostRMSE", fmt(real_post["rmse_cm"]))
    put("RealAuditPriorRMSE", fmt(real_prior["rmse_cm"]))

    field_baselines = read_json("outputs/field_baselines_2021/summary.json")
    baseline_metrics = {row["estimator"]: row for row in field_baselines["metrics"]}
    baseline_names = {
        "FieldEWMA": "EWMA (alpha=0.5)",
        "FieldMedian": "Running median (three images)",
        "FieldHolt": "Holt level-trend (alpha=0.5, beta=0.2)",
        "FieldGaussian": "Gaussian local-linear Kalman filter",
    }
    for prefix, label in baseline_names.items():
        row = baseline_metrics[label]
        put(prefix + "Bias", fmt(row["bias_cm"]))
        put(prefix + "MAE", fmt(row["mae_cm"]))
        put(prefix + "RMSE", fmt(row["rmse_cm"]))
        put(prefix + "Gain", fmt(row["baseline_minus_proposed_mae_cm"]))
        put(prefix + "GainLo", fmt(row["ci95_cm"][0]))
        put(prefix + "GainHi", fmt(row["ci95_cm"][1]))

    sensitivity = field_baselines["distributional_sensitivity"]
    median_sensitivity = sensitivity["median_absolute_error"]
    leave_one_out = sensitivity["leave_one_row_out_mae"]
    put("FieldMedianErrorSingle", fmt(median_sensitivity["single_frame_cm"]))
    put("FieldMedianErrorBayes", fmt(median_sensitivity["particle_filter_cm"]))
    put("FieldMedianErrorGain", fmt(median_sensitivity["reduction_cm"]))
    put("FieldMedianErrorGainLo", fmt(median_sensitivity["row_cluster_bootstrap_ci95_cm"][0]))
    put("FieldMedianErrorGainHi", fmt(median_sensitivity["row_cluster_bootstrap_ci95_cm"][1]))
    put("FieldLeaveOneRowOutN", leave_one_out["omissions"])
    put("FieldLeaveOneRowOutMinGain", fmt(leave_one_out["minimum_improvement_cm"]))
    put("FieldLeaveOneRowOutMaxGain", fmt(leave_one_out["maximum_improvement_cm"]))

    error_quantiles = pd.read_csv(
        ROOT / "outputs/field_baselines_2021/absolute_error_quantiles.csv"
    ).set_index("estimator")
    quantile_names = {
        "FieldSingle": "Single-frame image extent",
        "FieldEWMA": "EWMA (alpha=0.5)",
        "FieldMedian": "Running median (three images)",
        "FieldHolt": "Holt level-trend (alpha=0.5, beta=0.2)",
        "FieldGaussian": "Gaussian local-linear Kalman filter",
        "FieldBayes": "Robust Bayesian particle filter",
    }
    quantile_words = {
        25: "TwentyFive",
        50: "Fifty",
        75: "SeventyFive",
        90: "Ninety",
        95: "NinetyFive",
    }
    for prefix, label in quantile_names.items():
        for level, word in quantile_words.items():
            put(
                f"{prefix}Abs{word}",
                fmt(error_quantiles.loc[label, f"absolute_error_q{level:02d}_cm"]),
            )

    pos = pd.read_csv(ROOT / "outputs/future_position_reestimation/position_reestimation_comparison.csv")
    frozen = pos.iloc[0]
    sequential = pos.iloc[1]
    put("FrozenMatches", int(frozen["n_matched_detections"]))
    put("SequentialMatches", int(sequential["n_matched_detections"]))
    put("SequentialExtraMatches", int(sequential["n_matched_detections"] - frozen["n_matched_detections"]))
    put("FrozenTrackDistance", fmt(frozen["mean_track_distance"], 4))
    put("SequentialTrackDistance", fmt(sequential["mean_track_distance"], 4))
    provenance = read_json("outputs/online_study/tracking_provenance_repair.json")
    put(
        "PosteriorRootChanged",
        provenance["evidence"]["rows_where_posterior_root_differs_from_raw_root"],
    )

    sim = pd.read_csv(ROOT / "outputs/simulation_study/simulation_scenario_metrics.csv")
    put("SimulationScenarios", sim["scenario"].nunique())
    put("SimulationPlantsPerScenario", int(sim["n_plants"].iloc[0]))
    put("SimulationRMSEMin", fmt(sim["height_rmse_cm"].min()))
    put("SimulationRMSEMax", fmt(sim["height_rmse_cm"].max()))
    put("SimulationCoverageMin", fmt(100 * sim["coverage_95"].min(), 1))
    put("SimulationCoverageMax", fmt(100 * sim["coverage_95"].max(), 1))

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")

    per_rows = []
    for row in end.sort_values(["rowid", "plantid"]).itertuples():
        per_rows.append(
            f"{str(row.rowid).replace('_', r'\_')}-{str(row.plantid).replace('_', r'\_')} & "
            f"{row.height_true:.1f} & {row.height_est_cm:.1f} & {row.posterior_mean_cm:.1f} & "
            f"[{row.posterior_q025_cm:.1f}, {row.posterior_q975_cm:.1f}] \\\\"
        )
    PER_PLANT.write_text("\n".join(per_rows) + "\n", encoding="utf-8", newline="\n")
    print(f"Wrote {OUT}")
    print(f"Wrote {PER_PLANT}")


if __name__ == "__main__":
    main()
